<nav class="navbar">
    <div class="navbar-brand">
        Encrypt test
    </div>
</nav>

<?php if (isset($_GET['acao']) && $_GET['acao'] == 'sucesso') { ?>

    <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Well done!</strong> Your form was successfully submited!
    </div>

<?php } ?>


<div class="container">
    <div class="row">
        <div class="col">
            <form action="/encrypt" method='post'>
                <div class="form-group">
                    <label for="document">Document</label>
                    <input class="form-control" id="document" name="document" type="text" placeholder="User document...">
                </div>
                <div class="row">
                    <div class="form-group col-8">
                        <label for="creditCard">Credit Card Token</label>
                        <input class="form-control" id="creditCard" name="creditCard" type="text" placeholder="Credit card token...">
                    </div>
                    <div class="form-group col-4">
                        <label for="value">Value</label>
                        <input class="form-control" id="value" name="value" type="number">
                    </div>
                </div>
                <button class="btn btn-primary btn-lg" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>